### ISSUE TITLE
A problem with some blending mode

### ISSUE THREAD

**Issue by DeRaNGeR** [pmgl/microstudio#168] opened 2022-11-03 14:46 UTC
I was testing to create a light system with some blend mode. But there are some blend mode that create a problem. For now i tested xor and destination-in. These two create the problem i write below:

- you need two sprites:
  1. one an object to see with the light
  2. one sprite as a spot of the light
 
the code:
![image](https://user-images.githubusercontent.com/5565814/199752490-72fb51e5-10ea-4c06-b776-33d288e5f6d5.png)

the result in preview:
![image](https://user-images.githubusercontent.com/5565814/199752572-1a2c0a1d-3db3-4576-933f-e22f918c9c63.png)

the result on the final game:
![image](https://user-images.githubusercontent.com/5565814/199752669-247bd760-967f-4f41-b706-8a6faa336b4b.png)

As you can see, there are some buggy renders.

I attach here a test with destination-in that has the same result:
[nightriverside.zip](https://github.com/pmgl/microstudio/files/9930255/nightriverside.zip)

**Comment by DeRaNGeR** [comment] 2022-12-02 16:59
Nope. :(

**Comment by pmgl** [comment] 2023-03-02 12:45
I am closing this as it seems to be a browser bug, which I can't reproduce. If this continues to happen consistently for you, in different browsers, please create a minimal test case project and share it in a new issue :-)

**Closed by pmgl** 2023-03-02 12:45 UTC
